using System;
using System.Collections.Generic;
using System.Text;
using Langlearn.Domain.Enums;
using Langlearn.Domain.Entities.Japanese;

namespace Langlearn.Domain.Static.Japanese
{
    public static class Syllabary
    {
        public static readonly List<Syllable> Hiragana = new List<Syllable>
        {
            new Syllable("あ", "a", SyllabaryType.Hiragana),
            new Syllable("い", "i", SyllabaryType.Hiragana),
            new Syllable("う", "u", SyllabaryType.Hiragana),
            new Syllable("え", "e", SyllabaryType.Hiragana),
            new Syllable("お", "o", SyllabaryType.Hiragana),
            new Syllable("か", "ka", SyllabaryType.Hiragana),
            new Syllable("き", "ki", SyllabaryType.Hiragana),
            new Syllable("く", "ku", SyllabaryType.Hiragana),
            new Syllable("け", "ke", SyllabaryType.Hiragana),
            new Syllable("こ", "ko", SyllabaryType.Hiragana),
            new Syllable("さ", "sa", SyllabaryType.Hiragana),
            new Syllable("し", "shi", SyllabaryType.Hiragana),
            new Syllable("す", "su", SyllabaryType.Hiragana),
            new Syllable("せ", "se", SyllabaryType.Hiragana),
            new Syllable("そ", "so", SyllabaryType.Hiragana),
            new Syllable("た", "ta", SyllabaryType.Hiragana),
            new Syllable("ち", "chi", SyllabaryType.Hiragana),
            new Syllable("つ", "tsu", SyllabaryType.Hiragana),
            new Syllable("て", "te", SyllabaryType.Hiragana),
            new Syllable("と", "to", SyllabaryType.Hiragana),
            new Syllable("な", "na", SyllabaryType.Hiragana),
            new Syllable("に", "ni", SyllabaryType.Hiragana),
            new Syllable("ぬ", "nu", SyllabaryType.Hiragana),
            new Syllable("ね", "ne", SyllabaryType.Hiragana),
            new Syllable("の", "no", SyllabaryType.Hiragana),
            new Syllable("は", "ha", SyllabaryType.Hiragana),
            new Syllable("ひ", "hi", SyllabaryType.Hiragana),
            new Syllable("ふ", "fu", SyllabaryType.Hiragana),
            new Syllable("へ", "he", SyllabaryType.Hiragana),
            new Syllable("ほ", "ho", SyllabaryType.Hiragana),
            new Syllable("ま", "ma", SyllabaryType.Hiragana),
            new Syllable("み", "mi", SyllabaryType.Hiragana),
            new Syllable("む", "mu", SyllabaryType.Hiragana),
            new Syllable("め", "me", SyllabaryType.Hiragana),
            new Syllable("も", "mo", SyllabaryType.Hiragana),
            new Syllable("や", "ya", SyllabaryType.Hiragana),
            new Syllable("ゆ", "yu", SyllabaryType.Hiragana),
            new Syllable("よ", "yo", SyllabaryType.Hiragana),
            new Syllable("ら", "ra", SyllabaryType.Hiragana),
            new Syllable("り", "ri", SyllabaryType.Hiragana),
            new Syllable("る", "ru", SyllabaryType.Hiragana),
            new Syllable("れ", "re", SyllabaryType.Hiragana),
            new Syllable("ろ", "ro", SyllabaryType.Hiragana),
            new Syllable("わ", "wa", SyllabaryType.Hiragana),
            new Syllable("を", "wo", SyllabaryType.Hiragana),
            new Syllable("が", "ga", SyllabaryType.Hiragana),
            new Syllable("ぎ", "gi", SyllabaryType.Hiragana),
            new Syllable("ぐ", "gu", SyllabaryType.Hiragana),
            new Syllable("げ", "ge", SyllabaryType.Hiragana),
            new Syllable("ご", "go", SyllabaryType.Hiragana),
            new Syllable("ざ", "za", SyllabaryType.Hiragana),
            new Syllable("じ", "ji", SyllabaryType.Hiragana),
            new Syllable("ず", "zu", SyllabaryType.Hiragana),
            new Syllable("ぜ", "ze", SyllabaryType.Hiragana),
            new Syllable("ぞ", "zo", SyllabaryType.Hiragana),
            new Syllable("だ", "da", SyllabaryType.Hiragana),
            new Syllable("ぢ", "ji, dji", SyllabaryType.Hiragana),
            new Syllable("づ", "dzu, zu", SyllabaryType.Hiragana),
            new Syllable("で", "de", SyllabaryType.Hiragana),
            new Syllable("ど", "do", SyllabaryType.Hiragana),
            new Syllable("ば", "ba", SyllabaryType.Hiragana),
            new Syllable("び", "bi", SyllabaryType.Hiragana),
            new Syllable("ぶ", "bu", SyllabaryType.Hiragana),
            new Syllable("べ", "be", SyllabaryType.Hiragana),
            new Syllable("ぼ", "bo", SyllabaryType.Hiragana),
            new Syllable("ぱ", "pa", SyllabaryType.Hiragana),
            new Syllable("ぴ", "pi", SyllabaryType.Hiragana),
            new Syllable("ぷ", "pu", SyllabaryType.Hiragana),
            new Syllable("ぺ", "pe", SyllabaryType.Hiragana),
            new Syllable("ぽ", "po", SyllabaryType.Hiragana),
            new Syllable("ん", "n", SyllabaryType.Hiragana),
            new Syllable("きゃ", "kya", SyllabaryType.Hiragana)
        };

        public static readonly List<Syllable> Katakana = new List<Syllable>
        {
            new Syllable("ア", "a", SyllabaryType.Katakana),
            new Syllable("イ", "i", SyllabaryType.Katakana),
            new Syllable("ウ", "u", SyllabaryType.Katakana),
            new Syllable("エ", "e", SyllabaryType.Katakana),
            new Syllable("オ", "o", SyllabaryType.Katakana),
            new Syllable("カ", "ka", SyllabaryType.Katakana),
            new Syllable("キ", "ki", SyllabaryType.Katakana),
            new Syllable("ク", "ku", SyllabaryType.Katakana),
            new Syllable("ケ", "ke", SyllabaryType.Katakana),
            new Syllable("コ", "ko", SyllabaryType.Katakana),
            new Syllable("サ", "sa", SyllabaryType.Katakana),
            new Syllable("シ", "shi", SyllabaryType.Katakana),
            new Syllable("ス", "su", SyllabaryType.Katakana),
            new Syllable("セ", "se", SyllabaryType.Katakana),
            new Syllable("ソ", "so", SyllabaryType.Katakana),
            new Syllable("タ", "ta", SyllabaryType.Katakana),
            new Syllable("チ", "chi", SyllabaryType.Katakana),
            new Syllable("ツ", "tsu", SyllabaryType.Katakana),
            new Syllable("テ", "te", SyllabaryType.Katakana),
            new Syllable("ト", "to", SyllabaryType.Katakana),
            new Syllable("ナ", "na", SyllabaryType.Katakana),
            new Syllable("ニ", "ni", SyllabaryType.Katakana),
            new Syllable("ヌ", "nu", SyllabaryType.Katakana),
            new Syllable("ネ", "ne", SyllabaryType.Katakana),
            new Syllable("ノ", "no", SyllabaryType.Katakana),
            new Syllable("ハ", "ha", SyllabaryType.Katakana),
            new Syllable("ヒ", "hi", SyllabaryType.Katakana),
            new Syllable("フ", "fu", SyllabaryType.Katakana),
            new Syllable("ヘ", "he", SyllabaryType.Katakana),
            new Syllable("ホ", "ho", SyllabaryType.Katakana),
            new Syllable("マ", "ma", SyllabaryType.Katakana),
            new Syllable("ミ", "mi", SyllabaryType.Katakana),
            new Syllable("ム", "mu", SyllabaryType.Katakana),
            new Syllable("メ", "me", SyllabaryType.Katakana),
            new Syllable("モ", "mo", SyllabaryType.Katakana),
            new Syllable("ヤ", "ya", SyllabaryType.Katakana),
            new Syllable("ユ", "yu", SyllabaryType.Katakana),
            new Syllable("ヨ", "yo", SyllabaryType.Katakana),
            new Syllable("ラ", "ra", SyllabaryType.Katakana),
            new Syllable("リ", "ri", SyllabaryType.Katakana),
            new Syllable("ル", "ru", SyllabaryType.Katakana),
            new Syllable("レ", "re", SyllabaryType.Katakana),
            new Syllable("ロ", "ro", SyllabaryType.Katakana),
            new Syllable("ワ", "wa", SyllabaryType.Katakana),
            new Syllable("ヲ", "wo", SyllabaryType.Katakana),
            new Syllable("ガ", "ga", SyllabaryType.Katakana),
            new Syllable("ギ", "gi", SyllabaryType.Katakana),
            new Syllable("グ", "gu", SyllabaryType.Katakana),
            new Syllable("ゲ", "ge", SyllabaryType.Katakana),
            new Syllable("ゴ", "go", SyllabaryType.Katakana),
            new Syllable("ザ", "za", SyllabaryType.Katakana),
            new Syllable("ジ", "ji", SyllabaryType.Katakana),
            new Syllable("ズ", "zu", SyllabaryType.Katakana),
            new Syllable("ゼ", "ze", SyllabaryType.Katakana),
            new Syllable("ゾ", "zo", SyllabaryType.Katakana),
            new Syllable("ダ", "da", SyllabaryType.Katakana),
            new Syllable("ヂ", "ji", SyllabaryType.Katakana),
            new Syllable("ヅ", "zu, dzu", SyllabaryType.Katakana),
            new Syllable("デ", "de", SyllabaryType.Katakana),
            new Syllable("ド", "do", SyllabaryType.Katakana),
            new Syllable("バ", "ba", SyllabaryType.Katakana),
            new Syllable("ビ", "bi", SyllabaryType.Katakana),
            new Syllable("ブ", "bu", SyllabaryType.Katakana),
            new Syllable("ベ", "be", SyllabaryType.Katakana),
            new Syllable("ボ", "bo", SyllabaryType.Katakana),
            new Syllable("パ", "pa", SyllabaryType.Katakana),
            new Syllable("ピ", "pi", SyllabaryType.Katakana),
            new Syllable("プ", "pu", SyllabaryType.Katakana),
            new Syllable("ペ", "pe", SyllabaryType.Katakana),
            new Syllable("ポ", "po", SyllabaryType.Katakana),
            new Syllable("ン", "n", SyllabaryType.Katakana)
        };
    }
}
